name: Build and deploy

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - run: yarn
    - run: git config user.name "flapsnap" && git config user.email "noreply@example.com" && yarn deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
